# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brandon Prentice - Fab Academy
email: brandon.prentice@iu1.org
description: > # this means to ignore newlines until "baseurl:"
  This is the official archive for Brandon Prentice's Fab Academy 
  assignments. The Fab Academy was developed to teach hands-on skills 
  in fab labs and began as an outreach project from MIT’s Center for 
  Bits and Atoms.
baseurl: "/archives/2017/fablabiu1/students/418" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: IU1FabLab
github_username:  jekyll
gitlab_username:  BrandonPrentice

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
